In [1]:
import numpy
import urllib.request
import scipy.optimize
import random
from sklearn import svm
import gzip

print ("Reading data...")
tin = gzip.open('../RunningBikingTrainValidTest/cross_validation_set_running_and_biking.json.gz', 'rb')

train_list = []

for l in tin:
    l = l.decode('ascii')
    dic = eval(l)
    train_list.append(dic)

print ("done")

Reading data...
done


In [2]:
def generate_features(dataList):
    feature_list = []
    for data in dataList:
        curr_features = []
        curr_features.append(numpy.amin(data['speed']))
        curr_features.append(numpy.mean(data['speed']))
        curr_features.append(numpy.amax(data['speed']))
        #curr_features.append(numpy.amin(data['heart_rate']))
        #curr_features.append(numpy.mean(data['heart_rate']))
        #curr_features.append(numpy.amax(data['heart_rate']))
        
        feature_list.append(curr_features)
    return feature_list

In [3]:
X_train_list = generate_features(train_list)
y_train_list = [b['sport'] is 'run' for b in train_list]

In [ ]:
print("Starting")
from sklearn.model_selection import cross_val_score

print("Feature is HR only")
print("kernel is linear")
for i in range(-3,10):
    clf = svm.SVC(kernel = 'linear', C = 2**i)
    scores = cross_val_score(clf, X_train_list, y_train_list, cv = 5)
    
    print("C is {}".format(str(2**i)))
    print(scores)
    print("Accuracy: %0.6f (+/- %0.6f)" % (scores.mean(), scores.std() * 2))
    print()

Starting
Feature is HR only
kernel is linear
C is 0.125
[ 0.96788076  0.96504671  0.96761835  0.96620132  0.96562402]
Accuracy: 0.966474 (+/- 0.002213)

C is 0.25
[ 0.96788076  0.96504671  0.96761835  0.96620132  0.96562402]
Accuracy: 0.966474 (+/- 0.002213)

C is 0.5
[ 0.96788076  0.96504671  0.96761835  0.96620132  0.96562402]
Accuracy: 0.966474 (+/- 0.002213)

C is 1
[ 0.96788076  0.96504671  0.96761835  0.96620132  0.96562402]
Accuracy: 0.966474 (+/- 0.002213)

C is 2
[ 0.96788076  0.96504671  0.96767083  0.96620132  0.96562402]
Accuracy: 0.966485 (+/- 0.002235)

C is 4
[ 0.96788076  0.96504671  0.96761835  0.9662538   0.9656765 ]
Accuracy: 0.966495 (+/- 0.002192)

C is 8
[ 0.96788076  0.96504671  0.96761835  0.9662538   0.96562402]
Accuracy: 0.966485 (+/- 0.002208)



In [ ]:
print("kernel is rbf")
for i in range(-3,11):
    clf = svm.SVC(C = 2**i)
    scores = cross_val_score(clf, X_train_list, y_train_list, cv = 10)
    
    print("C is %d"%C)
    print(scores)
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
    print()

In [ ]:
print("kernel is poly")
for i in range(-3,11):
    clf = svm.SVC(kernel = 'poly', C = 2**i)
    scores = cross_val_score(clf, X_train_list, y_train_list, cv = 10)
    
    print("C is %d"%C)
    print(scores)
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
    print()

In [ ]:
print("kernel is sigmoid")
for i in range(-3,11):
    clf = svm.SVC(kernel = 'sigmoid', C = 2**i)
    scores = cross_val_score(clf, X_train_list, y_train_list, cv = 10)
    
    print("C is %d"%C)
    print(scores)
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
    print()